### ISSUE TITLE
Rapsberry Pi Imager makes SD cards unusable

### ISSUE THREAD

**Issue by RyanNgCT** [raspberrypi/imagewriter#28] opened 2020-03-09 12:17 UTC
My 32GB Samsung EVO micro-SDHC UHS-1 Card cannot be read with my Mac now after failing to be formatted with the Raspberry Pi Imager.

^ I commented this yesterday on the imager page.

**I would like to find out if there is a way to repair the sd card as it is not possible with Mac OS X Mojave's Disk Utility Application.**

Thanks.

Ryan

![Screenshot 2020-03-09 at 8 12 32 PM](https://user-images.githubusercontent.com/48358569/76212159-d0e12100-6242-11ea-8661-1420646d36a8.png)

Another user had a similar problem.
I quote:
"I have tested this application with 3 different SD cards and in all cases it fails. Moreover after retrying the procedure the SD card become unusable and my Windows 7 computer can not longer read it, it looks like that thy have been damaged by the tool.

I have used 1 32GB and 2 64GB and in all cases the 3 SD cards are broken due to the tool.

Have you experienced this problem?
Any workaround recover my damaged SD cards ?

Thanks,
Antonio"

**Comment by maxnet** [comment] 2020-03-09 12:19
Try the "erase" option in the Raspberry Pi Imager.

**Comment by RyanNgCT** [comment] 2020-03-09 12:21
The problem is the imager does not even detect the card though...
![Uploading Screenshot 2020-03-09 at 8.21.15 PM.png…]()

**Comment by RyanNgCT** [comment] 2020-03-09 12:22
the problem is the card does not even get detected...
![Screenshot 2020-03-09 at 8 21 15 PM](https://user-images.githubusercontent.com/48358569/76212558-b6f40e00-6243-11ea-926d-36b24689af17.png)

**Comment by RyanNgCT** [comment] 2020-03-09 12:24
Oops accidentally closed the issue...

**Comment by maxnet** [comment] 2020-03-09 12:30
When you insert a SD card without partition table, it should show you a dialog like this:

![64F51EE5-B920-40CD-95A7-65C636BE293D](https://user-images.githubusercontent.com/1123701/76213005-0584b680-620a-11ea-9596-69c1f2595745.jpeg)

Make sure you press "Ignore" there -and not "Eject"-
Then the card do should be visible in the imager.

**Comment by maxnet** [comment] 2020-03-09 12:33
BTW your screenshot shows "Writable: no"
Is it perhaps a full size SD card that has a switch on it to write protect it?

**Comment by RyanNgCT** [comment] 2020-03-09 12:45
Ok it works thanks for your help. But are there still issues with the imager?

**Comment by maxnet** [comment] 2020-03-09 12:47
There should not be a problem with images you download using the utility.
You may have with custom images (already fixed in source)

**Comment by RyanNgCT** [comment] 2020-03-09 12:48
Hmm but can I modify the image after it is flashed? I'm trying to do a headless Raspberry Pi 4 setup.

**Comment by RyanNgCT** [comment] 2020-03-09 12:48
Because I may need to set up the ssh and config files.

**Comment by maxnet** [comment] 2020-03-09 12:50
Just do not use the "use custom" option in the Imager until a new version is released.

**Comment by RyanNgCT** [comment] 2020-03-09 12:50
Ok noted with thanks!

**Closed** 2020-03-09 12:53 UTC

**Comment by lurch** [comment] 2020-03-14 17:02
> I may need to set up the ssh and config files.

#12 discussed that...

**Comment by ghollingworth** [comment] 2020-03-14 18:49
This issue has now been fixed, you can use the "use-custom" option again...  Just reinstall the application to pull in v1.2

**Comment by lars-dev** [comment] 2021-04-12 05:59
I seem to have the same problem. Two different micro SD cards are broken after use of Raspberry Pi Imager V1.6.1
Both cards are 16GB but different brands.

The first card was never fully able to get an image written on it. It now only shows um as Generic Storage in disk utility. 
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/62394789/114345168-89257b00-9b61-11eb-89d8-fa92653b3de4.png">

I tried to format the card with disk utility and terminal. It always shows the same error.
<img width="464" alt="image" src="https://user-images.githubusercontent.com/62394789/114345266-b3773880-9b61-11eb-96b4-dd753c6af8dc.png">

Same issue when trying to erase the card on a windows machine.

When i use the erase option of Raspberry Pi Imager it tells me that it was successful but basically nothing changed.
<img width="681" alt="image" src="https://user-images.githubusercontent.com/62394789/114345384-e4f00400-9b61-11eb-8e44-52359a220ae9.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/62394789/114345473-15d03900-9b62-11eb-9d9b-c77506956012.png">

After that when I try to write the image to the card it still shows: 
<img width="554" alt="image" src="https://user-images.githubusercontent.com/62394789/114345600-4f08a900-9b62-11eb-9c09-70944471c0f3.png">

this is the info I get in terminal
<img width="929" alt="image" src="https://user-images.githubusercontent.com/62394789/114345803-a9a20500-9b62-11eb-832b-3b699bd47b40.png">

When trying to format it with terminal i get the same error:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/62394789/114346079-20d79900-9b63-11eb-95dd-72347e65410c.png">

This shows up in System Information
<img width="653" alt="image" src="https://user-images.githubusercontent.com/62394789/114346742-3b5e4200-9b64-11eb-88ff-c5b11fc4b0f1.png">


I did a few restarts in between and tried again but nothing. So I assume it is broken. 





The second micro SD card is even weirder. 
It mouted normally and I was able to start writing the image to it with Raspberry Pi Imager. It went up to around 99% (maybe even 100%) and then gave me some error.
I thought, thats odd but since writing worked this time I just wanted to try again.
So i unplugged and the card, plugged it back in..... Nothing
No message about not having the correct file system, no indicator in disk utility, no list in terminal (diskutil list) ....nothing
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/62394789/114346536-ee7a6b80-9b63-11eb-9942-4983aeb28daf.png">

The only place I was able to find the card was in the System Information:
<img width="689" alt="image" src="https://user-images.githubusercontent.com/62394789/114346855-5fba1e80-9b64-11eb-88ea-075e2b5b626b.png">

When I try on a windows machine it will show up as /D: .  I am able to change that to  eg /E: but it does not have any partition or similar that I could address to be erased. 
Similar to mac it shows up as a USB Storage but I cant do anything with it.

So that card seems to be (even more) broken too.
The cards were both Class 10.

Any suggestions. I just want to avoid buying and immediately breaking new SD cards.

**Comment by lurch** [comment] 2021-04-12 08:19
Do you have a different SD card reader that it might be worth trying? I dunno if it'll help, but see also https://github.com/balena-io/etcher/blob/master/docs/USER-DOCUMENTATION.md#recovering-broken-drives

**Comment by lars-dev** [comment] 2021-04-12 08:50
Yes 
Sorry i did not mention that
Have two different card readers on hand.
Maybe I was just unlucky and the sd cards were close to their last days anyways

**Comment by lurch** [comment] 2021-04-12 09:31
As extensively explained [here](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive) it's not possible for application software to "break" SD cards.

**Comment by ghollingworth** [comment] 2021-04-13 06:20
Were they good quality branded SD cards?  i.e. something like Sandisk?

We currently only recommend Sandisk (we've been testing many different SD cards in an automated SD card test system and the Sandisk cards have been the most reliable so far).

**Comment by lars-dev** [comment] 2021-04-13 06:27
It seems like I just got unlucky. Got new SD Cards and they worked as they were supposed to. The other two cards are still "broken" though. 
And even if that might be the wrong word.... in the end of the day I can not use them anymore. That to me is broken.

**Comment by mnr** [comment] 2021-09-27 18:36
I have two 16gb PNY SD cards that exhibit this same problem. Both Mac, Windows, and RPi believe the disks are write-protected. This happened after reformatting them with the RPi Imager on a MacBook Pro with a USB C Hub Adapter. I'd be happy to mail these two cards to anyone with forensic chops to determine what's up.

I've already tried to remove write-protected files, tried hard-reformat, tried reformat with the SD card formatter from the SD card association, etc.

MNR

**Comment by Farmerbrown87** [comment] 2021-10-06 16:15
Hi, I am having the same issue and have 'bricked' four SD cards. Attempts made with the following bits...

hard
- Raspberry Pi 3 B+ 
- two × SanDisk Ultra 128 GB microSD cards
- two × SanDisk Extreme PRO 64 GB microSD cards (new)
soft 
- Raspberry Pi Imager v1.6.2
- Raspberry Pi OS (32-bit) release 2021-05-07
- Raspberry Pi OS Full (32-bit) release 2021-05-07

@mnr was the issue with the same version of the imager?

**Comment by Farmerbrown87** [comment] 2021-10-07 20:00
@lurch I have tried an old card-reader, Kingston MobileLite G3 (USB 3.0).
The first card I tried was [Anker USB C Hub](https://www.amazon.co.uk/gp/product/B07H4VQ4BZ/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1). 

I've successfully imaged a diet-pi OS for PiHole using the Anker hub for an OG Raspberry Pi.

I will borrow my partners Macbook and see if that works... watch this space!

**Comment by Farmerbrown87** [comment] 2021-10-12 11:43
Update. 
I have tried writing the microSD card with the Macbook and tried yet another SD card as well.
I have also purchased the official RPi power supply.

Still it is not working. 

What else can I troubleshoot here before I determine the RPi needs to go back to the supplier?

thanks in advance

**Comment by lurch** [comment] 2021-10-12 11:55
@Farmerbrown87 In an earlier message you said that RPi Imager was "bricking" your SD cards, and now you seem to be implying that the problem is only that your RPi isn't booting? Did the verification step in RPi Imager work?
For these kinds of non-booting support issues I think you'll get much more rapid and detailed help on the [forums](https://forums.raspberrypi.com/).

**Comment by MichaelVanEnde** [comment] 2022-05-19 08:57
I have encountered the same isseu with the v1.7.2 release. 
![image](https://user-images.githubusercontent.com/22372844/169254386-0775f2fb-f799-42c0-9d6f-324ee2df60b2.png)
I tried with 3 SD cards. with differend adapters. Even without changing the settings i encounter the problem.
the restore my SD cards i had to "Erase" it withe the RBP Imager and then i got the following errer:
![image](https://user-images.githubusercontent.com/22372844/169254839-2f74833a-58e2-4010-8267-acf66a6a539b.png)
after this error you can format the SD card again with via windows.

**Comment by crstrand** [comment] 2022-09-18 17:53
I am having the same issue with Imager 1.7.3
I first noticed it on the windows app (bricked 2 previously good 16GB cards) then with the linux app on ubuntu (bricked 1 32GB card).  All cards were verified good with f3 and the 2 16GB cards had worked in a pair of Pi0W for a few months.
I can't get any of the 16GB cards to be recognised by either my windows machine or my linux box.
I have tried multiple uSD readers and all have the same behavior with the cards.
I DID successfully image on 32GB card on the linux box, then the second card "bricked" with imager popping up a write error message.
I attempted to ressurect the 32GB card with `fsck`, `e2fsck`, `parted` and `mkfs`
However, the second 32GB card now reports 
```
sudo  f3probe --destructive /dev/sdi
F3 probe 8.0
Copyright (C) 2010 Digirati Internet LTDA.
This is free software; see the source for copying conditions.

WARNING: Probing normally takes from a few seconds to 15 minutes, but
         it can take longer. Please be patient.

Bad news: The device '/dev/sdi' is damaged
```
I know some posters have said the app can't brick cards, but the same behavior between two different computers, operating systems, and readers with the only similarity being the Raspberry Pi Imager app is VERY suspicious.
