### ISSUE TITLE
(Wishlist) Checkbox to enable SSH

### ISSUE THREAD

**Issue by probonopd** [raspberrypi/imagewriter#25] opened 2020-03-08 07:23 UTC
In many tutorials, it is mentioned that one has to create an empty file called `ssh` on the boot partition in order to enable SSH. It would be very useful if Imager had a checkbox that would, when checked, create this file automatically.

**Comment by dividuum** [comment] 2020-03-08 10:28
Duplicate of #12

**Closed** 2020-03-08 11:05 UTC
